# -*- coding: utf-8 -*-
"""
Django settings for teaguru project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'xxxxxxxxxxxxxxxxxxxxxxxx'

# SECURITY WARNING: don't run with debug turned on in production!
# ENABLE CACHE AND COMPRESSORS IN PRODUCTION!
DEBUG = False

ALLOWED_HOSTS = [u'xxxxxxx', u'xxxxxxx']

CART_SESSION_ID = 'cart'

USE_THOUSAND_SEPARATOR = True
# Application definition

INSTALLED_APPS = [
    'suit',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.sites',
    'haystack',
    'compressor',
#   'imagekit'
#   'easy_thumbnails',
#   'filer',
#   'mptt',
    'nested_inline',
    'django_user_agents',
    'ckeditor',
    'yandex_money',
    'ya_market',
    'teashop',
    'cart',
    'cupons',
    'orders',
    'payment',
    'account',
    'blog',
    'drip',
    'sellup',
#   'store',
]

SITE_ID = 1

HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
        'PATH': os.path.join(os.path.dirname(__file__), 'whoosh_index'),
        'INCLUDE_SPELLING': True,
    },
}

HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    }
}

CACHE_MIDDLEWARE_ALIAS = 'default'

CACHE_MIDDLEWARE_SECONDS = (60 * 60)

CACHE_MIDDLEWARE_KEY_PREFIX = 'teashop'

USER_AGENTS_CACHE = 'default'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'account.middleware.LocaleMiddleware',
    'account.middleware.TimezoneMiddleware',
#    'django.middleware.cache.UpdateCacheMiddleware',
    'htmlmin.middleware.HtmlMinifyMiddleware',
#    'django.middleware.cache.FetchFromCacheMiddleware',
    'htmlmin.middleware.MarkRequestMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',
]

ROOT_URLCONF = 'teaguru.urls'

FILER_CANONICAL_URL = 'shared/'

USER_AGENTS_CACHE = 'default'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart',
                'teashop.context_processors.common',
                'teashop.context_processors.user_agent',
                'teashop.context_processors.search',
                'account.context_processors.account',
                'sellup.context_processors.sellups',
            ],
        },
    },
]

TEMPLATED_EMAIL_BACKEND = 'templated_email.backends.vanilla_django.TemplateBackend'

STATICFILES_FINDERS = (
    'compressor.finders.CompressorFinder',
)

#COMPRESS_CSS_FILTERS = (
#    'compressor.filters.cssmin.rCSSMinFilter',    
#)

COMPRESS_JS_FILTERS = (
    'compressor.filters.jsmin.JSMinFilter',    
)

COMPRESS_ENABLED = True

WSGI_APPLICATION = 'teaguru.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'xxxxxxxx',
        'USER': 'xxxxxxxx',
        'PASSWORD': 'xxxxxxxx',
        'HOST': 'localhost',
        'PORT': '',
    }
}

# Excel import 
FILE_UPLOAD_HANDLERS = ("django_excel.ExcelMemoryFileUploadHandler",
                        "django_excel.TemporaryExcelFileUploadHandler")


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#Ckeditor
CKEDITOR_JQUERY_URL = '//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'
CKEDITOR_UPLOAD_PATH = "ck_uploads/"

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

TIME_ZONE = 'Europe/Moscow'

LANGUAGE_CODE = 'ru-ru'

USE_I18N = True

USE_L10N = True

USE_TZ = True

#Ya.Money
YANDEX_MONEY_DEBUG = False
YANDEX_MONEY_SCID = 0000000
YANDEX_MONEY_SHOP_ID = 0000000
YANDEX_MONEY_SHOP_PASSWORD = 'xxxxxxxxxxxx'
YANDEX_MONEY_FAIL_URL = 'xxxxxxxxxxxx'
YANDEX_MONEY_SUCCESS_URL = 'xxxxxxxxxxxxxxx'
YANDEX_MONEY_MAIL_ADMINS_ON_PAYMENT_ERROR = True

class PAYMENT_TYPE:
    NC = 'NC'
    PC = 'PC'
    AC = 'AC'
    GP = 'GP'
    MC = 'MC'
    WM = 'WM'
    SB = 'SB'
    AB = 'AB'
    MA = 'MA'
    PB = 'PB'
    QW = 'QW'
    QP = 'QP'

    CHOICES = (
        (NC, u'Наличными при получении'),
        (PC, u'Кошелек Яндекс.Деньги'),
        (AC, u'Банковская карта'),
        (GP, u'Наличными через кассы и терминалы'),
        (MC, u'Счет мобильного телефона'),
        (WM, u'Кошелек WebMoney'),
        (SB, u'Сбербанк: оплата по SMS или Сбербанк Онлайн'),
        (AB, u'Альфа-Клик'),
        (MA, u'MasterPass'),
        (PB, u'Интернет-банк Промсвязьбанка'),
        (QW, u'QIWI Wallet'),
        (QP, u'Доверительный платеж (Куппи.ру)'),
    )

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

DOCS_ROOT = os.path.join(BASE_DIR, 'downloads/')

STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
MEDIA_URL = '/media/'

#mail settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' 

EMAIL_HOST = 'xxxxxxxx'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'xxxxxxxxxxxxxxxxxx'
EMAIL_HOST_PASSWORD = 'xxxxxxxxxxxx'
