# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teashop', '0061_auto_20170415_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remainder', models.FloatField(default='0.00', verbose_name='\u041e\u0441\u0442\u0430\u0442\u043e\u043a \u043d\u0430 \u0441\u043a\u043b\u0430\u0434\u0435')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_item', to='teashop.Product', verbose_name='\u0422\u043e\u0432\u0430\u0440')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
        ),
        migrations.AddField(
            model_name='storeitem',
            name='supplier',
            field=models.ManyToManyField(related_name='store_item', to='store.Supplier', verbose_name='\u041f\u043e\u0441\u0442\u0430\u0432\u0449\u0438\u043a'),
        ),
    ]
