# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeitem',
            options={'verbose_name': '\u0422\u043e\u0432\u0430\u0440', 'verbose_name_plural': '\u0422\u043e\u0432\u0430\u0440\u044b'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': '\u041f\u043e\u0441\u0442\u0430\u0432\u0449\u0438\u043a', 'verbose_name_plural': '\u041f\u043e\u0441\u0442\u0430\u0432\u0449\u0438\u043a\u0438'},
        ),
        migrations.AddField(
            model_name='storeitem',
            name='date_upd',
            field=models.DateTimeField(auto_now=True, verbose_name='UPD'),
        ),
    ]
