# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20170416_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='supplier',
            field=models.ManyToManyField(blank=True, related_name='store_item', to='store.Supplier', verbose_name='\u041f\u043e\u0441\u0442\u0430\u0432\u0449\u0438\u043a'),
        ),
    ]
