# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teashop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[(b'kg', b'\xd0\xba\xd0\xb3.'), (b'gr', b'\xd0\xb3\xd1\x80.'), (b'wt', b'\xd1\x88\xd1\x82.')], max_length=11, verbose_name='Unit'),
        ),
    ]
