# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teashop', '0005_auto_20170114_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=b'0.00', max_digits=10, verbose_name='Price per unit'),
        ),
    ]
