# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teashop', '0006_auto_20170114_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='duration',
            field=models.CharField(default='5', max_length=160, verbose_name='Boiling duration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='temperature',
            field=models.CharField(default='1', max_length=160, verbose_name='Boiling temp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.CharField(default='5', max_length=160, verbose_name='Volume'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='brief',
            field=models.CharField(max_length=160, verbose_name='Brief descr for cat. view'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=160, verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=160, null=True, unique=True, verbose_name='Unique product slug'),
        ),
    ]
