# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teashop', '0010_category_has_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=b'previews', verbose_name='Preview image'),
        ),
    ]
