# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teashop', '0011_category_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name=b'\xd0\x98\xd0\xb4\xd0\xb5\xd0\xbd\xd1\x82\xd0\xb8\xd1\x84\xd0\xb8\xd0\xba\xd0\xb0\xd1\x82\xd0\xbe\xd1\x80 \xd0\xbf\xd0\xbe\xd0\xb4\xd0\xb1\xd0\xbe\xd1\x80\xd0\xba\xd0\xb8')),
                ('category', models.ManyToManyField(related_name='clists', to='teashop.Category')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u043f\u0443\u043b\u044f\u0440\u043d\u044b\u0435 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438',
                'verbose_name_plural': '\u041f\u043e\u043f\u0443\u043b\u044f\u0440\u043d\u044b\u0435 \u043a\u0430\u0438\u0435\u0433\u043e\u0440\u0438\u0438',
            },
        ),
    ]
