# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teashop', '0012_clist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clist',
            options={'verbose_name': '\u041f\u043e\u0434\u0431\u043e\u0440\u043a\u0430 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0439', 'verbose_name_plural': '\u041f\u043e\u0434\u0431\u043e\u0440\u043a\u0438 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0439'},
        ),
    ]
