# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teashop', '0013_auto_20170116_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clist',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u043f\u043e\u0434\u0431\u043e\u0440\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', '\u043a\u0433.'), ('gr', '\u0433\u0440.'), ('wt', '\u0448\u0442.')], max_length=11, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='prop',
            field=models.CharField(choices=[('c', '\u0446\u0432\u0435\u0442'), ('e', '\u044d\u0444\u0444\u0435\u043a\u0442'), ('m', '\u043f\u0440\u043e\u0438\u0437-\u043b\u044c')], max_length=30, verbose_name='Tag property'),
        ),
    ]
