# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teashop', '0014_auto_20170117_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopconfig',
            name='keywords_meta',
            field=models.TextField(blank=True, max_length=390, null=True, verbose_name='Keywords meta'),
        ),
    ]
