# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teashop', '0016_auto_20170119_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Product preview image'),
        ),
    ]
