# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 18:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teashop', '0018_auto_20170119_1957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optionalproductfield',
            options={'verbose_name': '\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0435 \u043f\u043e\u043b\u0435', 'verbose_name_plural': '\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0435 \u043f\u043e\u043b\u044f'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': '\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435', 'verbose_name_plural': '\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='has_child',
        ),
        migrations.AddField(
            model_name='product',
            name='articul',
            field=models.CharField(default='sde1', max_length=160, verbose_name='\u0410\u0440\u0442\u0438\u043a\u0443\u043b'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=False, verbose_name='\u0410\u043a\u0442\u0438\u0432\u0438\u0440\u043e\u0432\u0430\u0442\u044c?'),
        ),
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.IntegerField(choices=[(1, b'1'), (2, b'2'), (3, b'3')], verbose_name='\u0423\u0440\u043e\u0432\u0435\u043d\u044c'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a \u0432\u044b\u0432\u043e\u0434\u0430'),
        ),
        migrations.AlterField(
            model_name='category',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='previews', verbose_name='\u041f\u0440\u0435\u0432\u044c\u044e'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='\u0427\u041f\u0423'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=60, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='description',
            field=models.TextField(blank=True, max_length=501, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='\u0427\u041f\u0423'),
        ),
        migrations.AlterField(
            model_name='optionalproductfield',
            name='name',
            field=models.CharField(max_length=60, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='optionalproductfield',
            name='value',
            field=models.TextField(max_length=501, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=False, verbose_name='\u0410\u043a\u0442\u0438\u0432\u0438\u0440\u043e\u0432\u0430\u0442\u044c?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brief',
            field=models.CharField(max_length=160, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=501, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430 %'),
        ),
        migrations.AlterField(
            model_name='product',
            name='duration',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0437\u0430\u0432\u0430\u0440\u0438\u0432\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=160, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='product',
            name='netto',
            field=models.PositiveIntegerField(verbose_name='\u041c\u0430\u0441\u0441\u0430 \u043d\u0435\u0442\u0442\u043e'),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='\u041f\u0440\u0435\u0432\u044c\u044e'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='\u0426\u0435\u043d\u0430 \u0437\u0430 \u043e\u0434\u043d\u0443 \u0435\u0434\u0438\u043d\u0438\u0446\u0443'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=160, null=True, unique=True, verbose_name='\u0427\u041f\u0423'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.BooleanField(default=False, verbose_name='\u0412 \u043d\u0430\u043b\u0438\u0447\u0438\u0438?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='temperature',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='\u0422\u0435\u043c\u043f\u0435\u0440\u0430\u0442\u0443\u0440\u0430 \u0437\u0430\u0432\u0430\u0440\u0438\u0432\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', '\u043a\u0433.'), ('gr', '\u0433\u0440.'), ('wt', '\u0448\u0442.')], max_length=11, verbose_name='\u0415\u0434\u0438\u043d\u0438\u0446\u044b \u0438\u0437\u043c\u0435\u0440\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='\u041e\u0431\u044a\u0451\u043c \u043d\u0430 \u0447\u0430\u0439\u043d\u0438\u043a'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='meta_description',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='\u041c\u0435\u0442\u0430-\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='set',
            name='active',
            field=models.BooleanField(default=False, verbose_name='\u0410\u043a\u0442\u0438\u0432\u0438\u0440\u043e\u0432\u0430\u0442\u044c?'),
        ),
        migrations.AlterField(
            model_name='set',
            name='description',
            field=models.TextField(blank=True, max_length=501, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='set',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='set',
            name='name',
            field=models.CharField(max_length=60, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='set',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=120, null=True, unique=True, verbose_name='\u0427\u041f\u0423'),
        ),
        migrations.AlterField(
            model_name='shopconfig',
            name='currency',
            field=models.CharField(blank=True, max_length=10, verbose_name='\u0418\u043a\u043e\u043d\u043a\u0430 \u0432\u0430\u043b\u044e\u0442\u044b'),
        ),
        migrations.AlterField(
            model_name='shopconfig',
            name='keywords_meta',
            field=models.TextField(blank=True, max_length=390, null=True, verbose_name='\u041c\u0435\u0442\u0430-\u043a\u043b\u044e\u0447\u0438'),
        ),
        migrations.AlterField(
            model_name='shopconfig',
            name='location',
            field=models.CharField(blank=True, max_length=75, verbose_name='\u0410\u0434\u0440\u0435\u0441'),
        ),
        migrations.AlterField(
            model_name='shopconfig',
            name='name',
            field=models.CharField(default='teaguru', max_length=20, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='shopconfig',
            name='phone',
            field=models.CharField(max_length=18, verbose_name='\u0422\u0435\u043b. \u043d\u043e\u043c\u0435\u0440'),
        ),
        migrations.AlterField(
            model_name='shopconfig',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=160, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='prop',
            field=models.CharField(choices=[('c', '\u0446\u0432\u0435\u0442'), ('e', '\u044d\u0444\u0444\u0435\u043a\u0442'), ('m', '\u043f\u0440\u043e\u0438\u0437-\u043b\u044c')], max_length=30, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435 \u0442\u0435\u0433\u0430'),
        ),
    ]
