# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teashop', '0020_auto_20170120_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='product',
            name='duration',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0437\u0430\u0432\u0430\u0440\u0438\u0432\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='product',
            name='temperature',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='\u0422\u0435\u043c\u043f\u0435\u0440\u0430\u0442\u0443\u0440\u0430 \u0437\u0430\u0432\u0430\u0440\u0438\u0432\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='\u041e\u0431\u044a\u0451\u043c \u043d\u0430 \u0447\u0430\u0439\u043d\u0438\u043a'),
        ),
    ]
