# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teashop', '0025_auto_20170131_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='preview',
        ),
    ]
