# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teashop', '0027_product_date_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
        ),
        migrations.RemoveField(
            model_name='tag',
            name='prop',
        ),
        migrations.AddField(
            model_name='tag',
            name='propty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='teashop.Property'),
        ),
        migrations.AddField(
            model_name='category',
            name='props',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='teashop.Property'),
        ),
    ]
