# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teashop', '0028_auto_20170201_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='propty',
            new_name='prop',
        ),
    ]
