# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teashop', '0029_auto_20170201_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': '\u0424\u0438\u043b\u044c\u0442\u0440', 'verbose_name_plural': '\u0424\u0438\u043b\u044c\u0442\u0440\u044b'},
        ),
    ]
