# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teashop', '0034_auto_20170207_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='product',
            new_name='products',
        ),
        migrations.AddField(
            model_name='set',
            name='index',
            field=models.BooleanField(default=False, verbose_name='\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u043d\u0430 \u0433\u043b\u0430\u0432\u043d\u043e\u0439?'),
        ),
    ]
