# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teashop', '0036_auto_20170211_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopconfig',
            name='title',
            field=models.CharField(max_length=260, verbose_name='Title'),
        ),
    ]
