# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teashop', '0039_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('deliv', '\u0421\u043f\u043e\u0441\u043e\u0431 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438'), ('packg', '\u0423\u043f\u0430\u043a\u043e\u0432\u043a\u0430')], max_length=20, verbose_name='\u0422\u0438\u043f'),
        ),
    ]
