# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teashop', '0043_auto_20170226_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ordering',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a \u0441\u043e\u0440\u0442\u0438\u0440\u043e\u0432\u043a\u0438'),
        ),
    ]
