# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teashop', '0044_product_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vlm',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='\u041e\u0431\u044a\u0451\u043c s\u043d\u0430 \u0447\u0430\u0439\u043d\u0438\u043a'),
        ),
    ]
