# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teashop', '0050_auto_20170310_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_kwds',
            field=models.TextField(blank=True, max_length=660, verbose_name='\u041c\u0435\u0442\u0430-\u0442\u0435\u0433 keywords'),
        ),
    ]
