# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teashop', '0054_carousel_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='opt_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='\u0426\u0435\u043d\u0430 \u0437\u0430 \u043e\u0434\u043d\u0443 \u0435\u0434\u0438\u043d\u0438\u0446\u0443'),
        ),
    ]
