# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 08:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teashop', '0055_product_opt_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='\u0420\u0435\u0439\u0442\u0438\u043d\u0433'),
        ),
        migrations.AlterField(
            model_name='product',
            name='opt_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='\u041e\u043f\u0442\u043e\u0432\u0430\u044f \u0446\u0435\u043d\u0430 \u0437\u0430 \u043e\u0434\u043d\u0443 \u0435\u0434\u0438\u043d\u0438\u0446\u0443'),
        ),
    ]
