# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 17:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teashop', '0056_auto_20170326_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ('order', 'name')},
        ),
        migrations.AddField(
            model_name='slide',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a \u0441\u043e\u0440\u0442\u0438\u0440\u043e\u0432\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 star(s)'), (2, '2 star(s)'), (3, '3 star(s)'), (4, '4 star(s)'), (5, '5 star(s)')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='\u0420\u0435\u0439\u0442\u0438\u043d\u0433'),
        ),
    ]
