# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teashop', '0057_auto_20170326_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='icon',
            field=models.CharField(max_length=42, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0438\u043a\u043e\u043d\u043a\u0438'),
        ),
    ]
