# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teashop', '0059_auto_20170409_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='zak_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='\u0417\u0430\u043a\u0443\u043f\u043e\u0447\u043d\u0430\u044f \u0446\u0435\u043d\u0430 \u0437\u0430 \u043e\u0434\u043d\u0443 \u0435\u0434\u0438\u043d\u0438\u0446\u0443'),
        ),
    ]
