# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teashop', '0060_product_zak_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('order', 'name'), 'verbose_name': '\u0422\u043e\u0432\u0430\u0440', 'verbose_name_plural': '\u0422\u043e\u0432\u0430\u0440\u044b'},
        ),
        migrations.AddField(
            model_name='product',
            name='remainder',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='\u041e\u0441\u0442\u0430\u0442\u043e\u043a'),
        ),
    ]
