# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teashop', '0061_auto_20170415_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='remainder',
        ),
    ]
