# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 13:23
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='\u0423\u043d\u0438\u043a\u0430\u043b\u044c\u043d\u0430\u044f \u043f\u043e\u0434\u043f\u0438\u0441\u044c')),
                ('author', models.CharField(blank=True, default='\u0427\u0430\u0439\u043d\u044b\u0439 \u0413\u0443\u0440\u0443', max_length=120, verbose_name='\u0410\u0432\u0442\u043e\u0440 (\u0427\u0430\u0439\u043d\u044b\u0439 \u0413\u0443\u0440\u0443 \u043f\u043e \u0443\u043c\u043e\u043b\u0447\u0430\u043d\u0438\u044e)')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=220, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('body', ckeditor.fields.RichTextField(verbose_name='\u0421\u0442\u0430\u0442\u044c\u044f')),
                ('preview', models.ImageField(upload_to='blog', verbose_name='\u041f\u0440\u0435\u0432\u044c\u044e')),
                ('active', models.BooleanField(default=False, verbose_name='\u0410\u043a\u0442\u0438\u0432\u0438\u0440\u043e\u0432\u0430\u0442\u044c?')),
            ],
            options={
                'ordering': ('-pub_date',),
                'verbose_name': '\u0421\u0442\u0430\u0442\u044c\u044f',
                'verbose_name_plural': '\u0421\u0442\u0430\u0442\u044c\u0438',
            },
        ),
    ]
