# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170117_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='teaser',
            field=models.TextField(default='Some text here', max_length=180, verbose_name='\u041f\u043e\u0434\u0441\u0442\u0440\u043e\u0447\u043d\u0438\u043a'),
            preserve_default=False,
        ),
    ]
