# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170118_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='keywords_meta',
        ),
        migrations.AddField(
            model_name='post',
            name='meta_kwds',
            field=models.TextField(blank=True, max_length=660, verbose_name='\u041c\u0435\u0442\u0430-\u0442\u0435\u0433 keywords'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.Tag'),
        ),
    ]
