# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teashop', '0059_auto_20170409_1810'),
        ('blog', '0006_auto_20170314_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rel_products',
            field=models.ManyToManyField(blank=True, related_name='posts', to='teashop.Product', verbose_name='\u0421\u0432\u044f\u0437\u0430\u043d\u043d\u044b\u0435 \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u044b'),
        ),
    ]
