# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 14:45
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('slug', models.SlugField(allow_unicode=True, max_length=60, unique=True, verbose_name='\u041f\u043e\u0434\u043f\u0438\u0441\u044c')),
                ('body', ckeditor.fields.RichTextField(verbose_name='\u0422\u0435\u043b\u043e \u043e\u043a\u043d\u0430')),
                ('active', models.BooleanField(default=False)),
                ('duration', models.DurationField()),
            ],
        ),
    ]
