# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u043a\u0430\u0440\u0443\u0441\u0435\u043b\u0438')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('background', models.ImageField(upload_to='slides', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0441\u043b\u0430\u0439\u0434\u0430')),
                ('title', models.TextField(max_length=220, verbose_name='\u0422\u0438\u0442\u0443\u043b')),
                ('subtitle', models.TextField(blank=True, max_length=260, verbose_name='\u041f\u043e\u0434\u0441\u0442\u0440\u043e\u0447\u043d\u0438\u043a')),
                ('button', models.BooleanField(default=False, verbose_name='\u0423\u0441\u0442\u0430\u043d\u043e\u0432\u0438\u0442\u044c \u043a\u043d\u043e\u043f\u043a\u0443?')),
                ('button_text', models.CharField(blank=True, max_length=120, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043a\u043d\u043e\u043f\u043a\u0438')),
                ('link', models.URLField(verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='index.Carousel')),
            ],
        ),
    ]
