# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': '\u041a\u0430\u0440\u0443\u0441\u0435\u043b\u044c', 'verbose_name_plural': '\u041a\u0430\u0440\u0443\u0441\u0435\u043b\u0438'},
        ),
    ]
