# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teashop', '0011_category_preview'),
        ('index', '0002_auto_20170115_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u043f\u043e\u0434\u0431\u043e\u0440\u043a\u0438')),
                ('category', models.ManyToManyField(related_name='clists', to='teashop.Category')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u043f\u0443\u043b\u044f\u0440\u043d\u044b\u0435 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438',
                'verbose_name_plural': '\u041f\u043e\u043f\u0443\u043b\u044f\u0440\u043d\u044b\u0435 \u043a\u0430\u0438\u0435\u0433\u043e\u0440\u0438\u0438',
            },
        ),
    ]
