# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_clist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clist',
            name='category',
        ),
        migrations.DeleteModel(
            name='Clist',
        ),
    ]
