# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_money', '0002_auto_20170219_1533'),
        ('orders', '0003_auto_20170219_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yandex_money.Payment', verbose_name=b'\xd0\x9f\xd0\xbb\xd0\xb0\xd1\x82\xd1\x91\xd0\xb6'),
        ),
    ]
