# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20170220_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_method',
            new_name='payment_type',
        ),
    ]
